/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas.pbo;




import javax.imageio.ImageIO;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.WriterException;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import java.awt.image.BufferedImage;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author LENOVO
 */
public class Pembayaran extends javax.swing.JFrame {
    float totalHarga;
    String jenisPembelian;
    
     public Pembayaran(){
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        DBConnector.initDBConnection();
    }
    
    public Pembayaran(float totalHarga, String jenisPembelian) {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        DBConnector.initDBConnection();
        this.totalHarga = totalHarga;
        this.jenisPembelian = jenisPembelian;
        int totalBelanjaInt = (int)totalHarga;
        
        tf_totalPembayaran.setText(String.format("%,d",totalBelanjaInt));
        
        generateIDPembayaran();
        Timer timer = new Timer(1000, e -> {
            updateTime();
        });
        timer.start();
        String idPembayaran = tf_idPembayaran.getText();
        String totalHargaQRIS = tf_totalPembayaran.getText();
        String qrCodeText = "Terimakasih telah melakukan pembayaran dengan ID "+idPembayaran+" Dengan Total Harga "+totalHargaQRIS; 
        int size = 200;

        String fileType = "png";
        String filePath = "qr_code.png";

            try {
                    
                QRCodeWriter qrCodeWriter = new QRCodeWriter();
                BitMatrix bitMatrix = qrCodeWriter.encode(qrCodeText, BarcodeFormat.QR_CODE, size, size);

                BufferedImage bufferedImage = new BufferedImage(size, size, BufferedImage.TYPE_INT_RGB);
                bufferedImage.createGraphics();

               for (int x = 0; x < size; x++) {
                    for (int y = 0; y < size; y++) {
                        int grayValue = (bitMatrix.get(x, y) ? 0 : 1) & 0xff;
                        bufferedImage.setRGB(x, y, (grayValue == 0 ? 0 : 0xFFFFFF));
                        }
                    }

                    Image scaledImage = bufferedImage.getScaledInstance(qrButton.getWidth(), qrButton.getHeight(), Image.SCALE_SMOOTH);
                    qrButton.setIcon(new ImageIcon(scaledImage));

                    File qrFile = new File(filePath);
                    ImageIO.write(bufferedImage, fileType, qrFile);
                } catch (WriterException | IOException ex) {
                    ex.printStackTrace();   
            }
    }
    
    private void generateIDPembayaran(){
          try {
            Statement stmt = DBConnector.connection.createStatement();
            String sql = "SELECT COUNT(*) as jumlah_pembayaran FROM pembayaran";
            ResultSet rs = stmt.executeQuery(sql);
            rs.next();
            int JumlahData = rs.getInt("jumlah_pembayaran");
            System.out.println(JumlahData);
            int GeneralID = JumlahData+1;
            String idTransString = String.format("PR%03d", GeneralID);

            tf_idPembayaran.setText(idTransString);   
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
              
        }
    }
    
    
    private void updateTime() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        String formattedDate = now.format(formatter);
        tf_waktu.setText(formattedDate);

    }
    
    
       

       
    
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_idPembayaran = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_waktu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_totalPembayaran = new javax.swing.JTextField();
        BayarDebit = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_cashDiterima = new javax.swing.JTextField();
        tf_kembalian = new javax.swing.JTextField();
        BayarCash = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_noDebit = new javax.swing.JTextField();
        tf_namaBank = new javax.swing.JTextField();
        btn_BayarDebit = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        qrButton = new javax.swing.JLabel();
        btn_konfirmasiQRIS = new javax.swing.JToggleButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PAYMENT PAGE");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" ID Pembayaran : ");

        tf_idPembayaran.setEditable(false);
        tf_idPembayaran.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_idPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idPembayaranActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tanggal & Waktu :");

        tf_waktu.setEditable(false);
        tf_waktu.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total Pembayaran :");

        tf_totalPembayaran.setEditable(false);
        tf_totalPembayaran.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(294, 294, 294))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_idPembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(tf_totalPembayaran))
                .addGap(37, 37, 37)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(tf_waktu, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_idPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tf_waktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_totalPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        BayarDebit.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setText("Uang Diterima :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setText("Kembalian :");

        tf_cashDiterima.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tf_cashDiterima.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_cashDiterima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cashDiterimaActionPerformed(evt);
            }
        });
        tf_cashDiterima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_cashDiterimaKeyReleased(evt);
            }
        });

        tf_kembalian.setEditable(false);
        tf_kembalian.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tf_kembalian.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        BayarCash.setText("Bayar");
        BayarCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BayarCashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BayarCash)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_cashDiterima)
                            .addComponent(tf_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_cashDiterima, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BayarCash, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        BayarDebit.addTab("Cash Payment", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel11.setText("Nomor Kartu :");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel12.setText("Bank :");

        btn_BayarDebit.setText("Bayar");
        btn_BayarDebit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BayarDebitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_noDebit)
                            .addComponent(tf_namaBank, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_BayarDebit))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_noDebit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_namaBank, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_BayarDebit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        BayarDebit.addTab("Debit Payment", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        qrButton.setBackground(new java.awt.Color(255, 255, 255));

        btn_konfirmasiQRIS.setBackground(new java.awt.Color(254, 254, 254));
        btn_konfirmasiQRIS.setText("Konfirmasi");
        btn_konfirmasiQRIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_konfirmasiQRISActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(qrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(btn_konfirmasiQRIS)
                .addGap(191, 191, 191))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(qrButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(btn_konfirmasiQRIS, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );

        BayarDebit.addTab("QR Code Payment", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BayarDebit)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BayarDebit, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void BayarCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BayarCashActionPerformed
        String uangDiterima = tf_cashDiterima.getText();
        uangDiterima = uangDiterima.replace(",", "");
        float totalBelanja = Float.parseFloat(uangDiterima);
        
        String kembalian = tf_kembalian.getText();
        kembalian = kembalian.replace(",", "");
        float kembalianFloat = Float.parseFloat(kembalian);
     
        Cash kas = new Cash(kembalianFloat, totalBelanja);
        
        String totalHargaString = tf_totalPembayaran.getText();
        totalHargaString = totalHargaString.replace(",", "");
        float totalHargaFloat = Float.parseFloat(totalHargaString);
        kas.setTotalHarga(totalHargaFloat);
        
        String waktuPembayaran = tf_waktu.getText();
        kas.setWaktuPembayaran(waktuPembayaran);
        
        String IDPembayaran = tf_idPembayaran.getText();
        String formattedOutput = IDPembayaran.substring(2);
        int result = Integer.parseInt(formattedOutput);
        kas.setIDPembayaran(result);
        
        String jenis = jenisPembelian.substring(0,2);
        
        if(jenis.equals("PL")){
            JOptionPane.showMessageDialog(this,"Pulsa Telah Terkirim");
        } else if(jenis.equals("TN")){
            TokenFrame frame = new TokenFrame();
            frame.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Pembayaran Berhasil");
            MainWindow frame = new MainWindow();
            frame.setVisible(true);
            this.dispose();
        }

        try {
            kas.simpanDatabase();
            generateIDPembayaran();
        } catch (SQLException ex) {
            Logger.getLogger(Pembayaran.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.dispose();
    }//GEN-LAST:event_BayarCashActionPerformed

    private void tf_idPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idPembayaranActionPerformed

    private void btn_BayarDebitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BayarDebitActionPerformed
        String namaBank = tf_namaBank.getText();
        String noKartu = tf_noDebit.getText();
        
        KartuDebit debit = new KartuDebit(namaBank, noKartu);
        
        String totalHargaString = tf_totalPembayaran.getText();
        totalHargaString = totalHargaString.replace(",", "");
        float totalHargaFloat = Float.parseFloat(totalHargaString);
        debit.setTotalHarga(totalHargaFloat);
        
        String waktuPembayaran = tf_waktu.getText();
        debit.setWaktuPembayaran(waktuPembayaran);
        
        String IDPembayaran = tf_idPembayaran.getText();
        String formattedOutput = IDPembayaran.substring(2);
        int result = Integer.parseInt(formattedOutput);
        debit.setIDPembayaran(result);
        
        String jenis = jenisPembelian.substring(0,2);
        
       if(jenis.equals("PL")){
            JOptionPane.showMessageDialog(this,"Pulsa Telah Terkirim");
        } else if(jenis.equals("TN")){
            TokenFrame frame = new TokenFrame();
            frame.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Pembayaran Berhasil");
            MainWindow frame = new MainWindow();
            frame.setVisible(true);
            this.dispose();
        }

        try {
            debit.simpanDatabase();
            generateIDPembayaran();
        } catch (SQLException ex) {
            Logger.getLogger(Pembayaran.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.dispose();
    }//GEN-LAST:event_btn_BayarDebitActionPerformed

    private void tf_cashDiterimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cashDiterimaActionPerformed
        String totalbelanja = tf_totalPembayaran.getText();
        String stringTotalBelanja = totalbelanja.replace(",", "");

        float totalBelanja = Float.parseFloat(stringTotalBelanja);
        int totalBelanjaInt = (int)totalBelanja;

        String bayar = tf_cashDiterima.getText();
        String stringBayar = bayar.replace(",", "");

        float dibayar = Float.parseFloat(stringBayar);
        int dibayarInt = (int)dibayar;

        int uang_kembali = dibayarInt - totalBelanjaInt;
        if(dibayar >= totalBelanjaInt){
             tf_kembalian.setText(String.format("%,d",uang_kembali));
        } 
        else {
             JOptionPane.showMessageDialog(this, "Uang Anda Kurang","ERROR MONEY",JOptionPane.ERROR_MESSAGE);
             tf_kembalian.setText("");
            }
    }//GEN-LAST:event_tf_cashDiterimaActionPerformed

    private void tf_cashDiterimaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_cashDiterimaKeyReleased
        String dibayarCash = tf_cashDiterima.getText();
        dibayarCash = dibayarCash.replace(",", "");

        if (dibayarCash.matches("\\d+")) {
            long dibayarInput = Long.parseLong(dibayarCash);
            String formattedInput = String.format("%,d", dibayarInput);
            tf_cashDiterima.setText(formattedInput);
        } else {
            JOptionPane.showMessageDialog(this, "Anda memasukkan huruf, silakan masukkan angka", "INPUT ERROR", JOptionPane.ERROR_MESSAGE);
            tf_cashDiterima.setText("");
        }
    }//GEN-LAST:event_tf_cashDiterimaKeyReleased

    private void btn_konfirmasiQRISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_konfirmasiQRISActionPerformed
     
        QRIS qris = new QRIS();
        
        String totalHargaString = tf_totalPembayaran.getText();
        totalHargaString = totalHargaString.replace(",", "");
        float totalHargaFloat = Float.parseFloat(totalHargaString);
        qris.setTotalHarga(totalHargaFloat);
        
        String waktuPembayaran = tf_waktu.getText();
        qris.setWaktuPembayaran(waktuPembayaran);
        
        String IDPembayaran = tf_idPembayaran.getText();
        String formattedOutput = IDPembayaran.substring(2);
        int result = Integer.parseInt(formattedOutput);
        qris.setIDPembayaran(result);
        
        String jenis = jenisPembelian.substring(0,2);
        
       if(jenis.equals("PL")){
            JOptionPane.showMessageDialog(this,"Pulsa Telah Terkirim");
        } else if(jenis.equals("TN")){
            TokenFrame frame = new TokenFrame();
            frame.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Pembayaran Berhasil");
            MainWindow frame = new MainWindow();
            frame.setVisible(true);
            this.dispose();
        }

        try {
            qris.simpanDatabase();
            generateIDPembayaran();
        } catch (SQLException ex) {
            Logger.getLogger(Pembayaran.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.dispose();
    }//GEN-LAST:event_btn_konfirmasiQRISActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BayarCash;
    private javax.swing.JTabbedPane BayarDebit;
    private javax.swing.JButton btn_BayarDebit;
    private javax.swing.JToggleButton btn_konfirmasiQRIS;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel qrButton;
    private javax.swing.JTextField tf_cashDiterima;
    private javax.swing.JTextField tf_idPembayaran;
    private javax.swing.JTextField tf_kembalian;
    private javax.swing.JTextField tf_namaBank;
    private javax.swing.JTextField tf_noDebit;
    private javax.swing.JTextField tf_totalPembayaran;
    private javax.swing.JTextField tf_waktu;
    // End of variables declaration//GEN-END:variables
}
